---
# tasks file for tomcat-prod
- name: Ensure tomcat is present
  apt: name={{item}} state=present
  with_items:
    - tomcat8
    - default-jdk
- name: Copy WAR file from host to remote vm
  copy:
    src: /root/roles2/hello-1.0.war
    dest: /var/lib/tomcat8/webapps/
- name: Ensure tomcat8 is started
  service:
    name: tomcat8
    state: started
